# include:
#   - project: 'group/subgroup/project'
#     ref: "main"
#     file: '/Application-cd.gitlab-ci.yml'
#   - local: 'logical-environment.gitlab-ci.yml'

default:
  interruptible: true

variables:
  DEFAULT_RUNNER: europa

stages:
  - build-image
  - push-image

build-container-image:
  stage: build-image
  tags:
    - ${DEFAULT_RUNNER}
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
  artifacts:
    paths:
      # Specify the files to be saved as artifacts
      - Dockerfile

push-image-to-registry:
  stage: push-image
  tags:
    - ${DEFAULT_RUNNER}
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $CI_REGISTRY_IMAGE
