
stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    # - docker build -t 192.168.1.221:5050/smith8ca/smith8ca-ddclient-api .
  artifacts:
    paths:
      - Dockerfile
      - docker-image.tar
  tags:
    - europa

push:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker login 192.168.1.221:5050
    - docker push $CI_REGISTRY_IMAGE
    # - docker push 192.168.1.221:5050/smith8ca/smith8ca-ddclient-api
  tags:
    - europa
