---
networks:
  default:
    external: true
    name: docker-shared

services:
  ddclient-api:
    container_name: ddclient-api
    environment:
      - DDCLIENT_INTERVAL=${DDCLIENT_INTERVAL}
      - HEALTHCHECKS_URL=${HEALTHCHECKS_URL}
      - HEALTHCHECKS_ID=${HEALTHCHECKS_ID}
    image: ddclient-api-container:latest
    ports:
      - ${PORT:-5000}:8000
    volumes:
      - ./src/config/ddclient.conf:/tmp/ddclient.conf:ro
      - ./src/ssl/ca.pem:/etc/ssl/certs/ca.pem:ro
