services:
  ddclient-api:
    image: ddclient-api-container:latest
    container_name: ddclient-api
    ports:
      - "8000:8000"
    environment:
      - DDCLIENT_INTERVAL=360m # Optional: Update interval
      - HEALTHCHECKS_URL=https://example.lan # Optional: Healthchecks.io URL
      - HEALTHCHECKS_ID=YOUR-UNIQUE-ID # Optional: Healthchecks.io UUID
      - HEALTHCHECKS_CUSTOM_CA=false # Optional: Use custom CA certificate
    volumes:
      - /path/to/your/ca.pem:/etc/ssl/certs/ca.pem:ro # Optional: Custom CA certificate
      - /path/to/your/ddclient.conf:/tmp/ddclient.conf:ro # Optional: Custom ddclient configuration
